/**
 * Normalized schema shared by every source.
 *
 * Only the two data shapes live here for now. A common `Source` interface is
 * intentionally NOT defined yet — it gets extracted once a second source
 * (YouTube) exists and the real duplication is visible.
 */

export type SourceKind = "hackernews" | "youtube" | "x" | "rss";

export interface Comment {
  id: string;
  author: string;
  /** Unix epoch seconds. */
  timestamp: number;
  /** Plain text (HTML already stripped). */
  text: string;
  /** Nesting depth in the comment tree; 0 = top-level. */
  depth: number;
  /** Engagement metrics (X posts); unset for sources without them (HN). */
  metrics?: { likes?: number; reposts?: number; replies?: number };
}

export interface Item {
  id: string;
  source: SourceKind;
  title: string;
  author: string;
  /** Unix epoch seconds. */
  timestamp: number;
  /** Article / self-text / transcript / thread text. Empty for link-only posts. */
  body: string;
  /** Flattened comment list (depth preserved on each comment). */
  comments: Comment[];
  /** Source-specific extras. */
  metadata: ItemMetadata;
}

export interface TranscriptSegment {
  /** Start offset from the beginning of the video, in milliseconds. */
  offsetMs: number;
  text: string;
}

export interface ItemMetadata {
  /** External link the item points to (HN story url, video url, ...). */
  url?: string;
  /** Discussion/permalink on the source itself. */
  permalink?: string;
  points?: number;
  numComments?: number;
  // YouTube extras
  views?: number;
  durationSec?: number;
  /** Raw transcript segments, kept so `--timestamps` can render offsets. */
  transcript?: TranscriptSegment[];
  /** Language of the transcript (e.g. "en"), and whether it was auto-generated. */
  transcriptLang?: string;
  transcriptAuto?: boolean;
  /** Transcript was generated by an LLM (Gemini) rather than extracted. */
  generatedBy?: "gemini";
  // X extras
  /** Trend volume, when the trends endpoint reports it. */
  tweetCount?: number;
  /** The search query behind an X item. */
  query?: string;
  // RSS extras
  /** Title of the feed an item came from. */
  feedTitle?: string;
  [key: string]: unknown;
}
